[tool.poetry]
name = "test-renovate-star"
version = "0.1.0"
description = ""
authors = ["Tom Forbes <tom@tomforb.es>"]

[tool.poetry.dependencies]
python = "^3.9"
boto3 = "*"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
